import generateErrorUtil from '../../utils/generateErrorUtil.js';

const getHackathonDetailsController = (req, res, next) => {
    try {
        const { hackathonId } = req.params;
        const hackathon = getHackathonById(hackathonId);
        if (!hackathon) {
            generateErrorUtil('Hackathon no encontrado', 404);
        }
        res.send({
            status: 'ok',
            message: 'hackathon obtenido',
            data: hackathon,
        });
    } catch (err) {
        next(err);
    }
};
export default getHackathonDetailsController;
